package edu.grinnell.csc207.soundsofsorting.sorts;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        
        for (int i = 1; i < arr.length; i++) {
            for (int j = 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, j - 1));
                
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<>(j, j - 1));
                    new SwapEvent<>(j, j - 1).apply(arr);
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        
        List<SortEvent<T>> events = new ArrayList<>();
        
        for (int i = 0; i < arr.length - 1; i++) {
            int min = i;
            for (int j = i + 1; j < arr.length; j++) {
                events.add(new CompareEvent<>(j, min));
                
                if (arr[j].compareTo(arr[min]) < 0) {
                    min = j;
                }
            }
            if (min != i) {
                events.add(new SwapEvent<>(i, min)); 
                new SwapEvent<>(i, min).apply(arr);
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        
        for (int i = 1; i < arr.length; i++) {
            for (int j = i; j > 0; j--) {
                events.add(new CompareEvent<>(j, j - 1));
                
                if (arr[j].compareTo(arr[j - 1]) < 0) {
                    events.add(new SwapEvent<>(j, j - 1)); 
                    new SwapEvent<>(j, j - 1).apply(arr);
                    
                } else {
                    break;
                }
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(
            T[] arr) {
        
        List<SortEvent<T>> events = new ArrayList<>();
        
        if (arr.length > 0) {
            mergeSortRecursion(arr, 0, arr.length - 1, events);
        }
        return events;
    }
    

     /**
     * Sorts the array according to the merge sort algorithm:
     * <pre>
     * [ sorted | sorted ] -> [ sorted ]
     * </pre>
     *
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param left The left bound of the subarray we want to sort
     * @param right The left bound of the subarray we want to sort
     * @param mid The midpoint of the subarray
     * @param events
     */
    public static <T extends Comparable<? super T>> void merge(T[] arr, int left, int right, int mid, List<SortEvent<T>> events) {
        
        
        int leftSize = mid - left + 1;
        int rightSize = right - mid;

        T[] leftArr = Arrays.copyOfRange(arr, left, mid + 1);
        T[] rightArr = Arrays.copyOfRange(arr, mid + 1, right + 1);

        int i = 0;
        int j = 0;
        int k = left;

        while (i < leftSize && j < rightSize) {
            events.add(new CompareEvent<>(left + i, mid + 1 + j));

            if (leftArr[i].compareTo(rightArr[j]) <= 0) {
                events.add(new CopyEvent<>(leftArr[i], k));
                new CopyEvent<>(leftArr[i], k).apply(arr);
                i++;
                k++;
            } else {
                events.add(new CopyEvent<>(rightArr[j], k));
                new CopyEvent<>(rightArr[j], k).apply(arr);
                j++;
                k++;
            }
        }

        while (i < leftSize) {
            events.add(new CopyEvent<>(leftArr[i], k));
            new CopyEvent<>(leftArr[i], k).apply(arr);
            i++;
            k++;
        }

        while (j < rightSize) {
            events.add(new CopyEvent<>(rightArr[j], k));
            new CopyEvent<>(rightArr[j], k).apply(arr);
            j++;
            k++;
        }
    }
    
    /**
     * This helper function recursively breaks down the left side of the array and
     * right side of the array and then merges it back up.
     * @param <T>
     * @param arr the array to sort
     * @param left The left bound of the subarray we want to sort
     * @param right
     * @param events
     */
    public static <T extends Comparable<? super T>> void mergeSortRecursion (T[] arr, int left, int right, List<SortEvent<T>> events) {
        
        if (left < right) {

            int mid = left + (right - left) / 2;

            //sort left
            mergeSortRecursion(arr, left, mid, events);

            //sort right
            mergeSortRecursion(arr, mid + 1, right, events);

            //merge
            merge(arr, left, right, mid, events);
        }
    }


    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        
        quickSortRecursion(arr, 0, arr.length - 1, events);
        
        return events;
    }
    
    /**
     * Splits into two by using bounds recursively, while using the quick sort method
     * of comparison using pivot points
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param left left bound of the subarray
     * @param right right bound of the subarray
     * @param events
     */
    public static <T extends Comparable<? super T>> void quickSortRecursion(T[] arr, int left, int right, List<SortEvent<T>> events) {
        //call on left and right
        if (left < right) {
            int pivot = pivotCompare(arr, left, right, events);

            //right side
            quickSortRecursion(arr, pivot + 1, right, events);

            //left side
            quickSortRecursion(arr, left, pivot - 1, events);
        }
    }
    
    /**
     * making the pivot the right most element
     * and using the pivot comparison from the quick sort method
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param left left bound of the subarray
     * @param right right bound of the
     * @param events
     * @return the pivot point which is the midpoint of the next recursion call
     */
    public static <T extends Comparable<? super T>> int pivotCompare(T[] arr, int left, int right, List<SortEvent<T>> events) {

        int pivot = right;
        int head = left;
        int tail = left - 1;

        while (head <= right - 1) {
            events.add(new CompareEvent<>(head, pivot));
            if (arr[head].compareTo(arr[pivot]) < 0) {
                tail++;
                events.add(new SwapEvent<>(head, tail));
                new SwapEvent<>(head, tail).apply(arr);
            }
            head++;
        }
        //do final swap with pivot and tail + 1
        events.add(new SwapEvent<>(tail + 1, pivot));
        new SwapEvent<>(tail + 1, pivot).apply(arr);
        
        return tail + 1;
    }
    
    /**
     * Sorts the array according to the heap sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return 
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> heapSort(T[] arr) {
        
        List<SortEvent<T>> events = new ArrayList<>();
        
        // Build max heap (start from the last root
        for (int i = arr.length / 2 - 1; i >= 0; i--) {
            makeHeap(arr, arr.length, i, events);
        }
        
        // Extract elements from the heap one by one
        for (int i = arr.length - 1; i > 0; i--) {
            swap(arr, 0, i);
            makeHeap(arr, i, 0, events); // Heapify the reduced heap
        }
        
        return events;
    }
    
    /**
     * Maintains the max heap property.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param n number of elements in heap
     * @param root the root index being heapified
     * @param events
     */
    public static <T extends Comparable<? super T>> void makeHeap(T[] arr, int n, int root, List<SortEvent<T>> events) {
        int largest = root;
        int left = 2 * root + 1;
        int right = 2 * root + 2;

        events.add(new CompareEvent<>(left, largest));
        if (left < n && arr[left].compareTo(arr[largest]) > 0) {
            largest = left;
        }

        events.add(new CompareEvent<>(right, largest));
        if (right < n && arr[right].compareTo(arr[largest]) > 0) {
            largest = right;
        }

        // Swap and continue heapifying if the root is not the largest
        if (largest != root) {
            events.add(new SwapEvent<>(root, largest));
            new SwapEvent<>(root, largest).apply(arr);
            makeHeap(arr, n, largest, events);
        }
    }
    
    public static <T extends Comparable<? super T>> void eventSort(T[] l, List<SortEvent<T>> events){
        for (SortEvent<T> event : events) {
            event.apply(l);
        }
    }
}
